before_script:
  - mysql -e 'create database constructeev_test;'
language: ruby
rvm:
- 2.2.2
addons:
  code_climate:
    repo_token:
      secure: p9sbaqbfhXusoZTw1yvjHkAvEzpA6E3TRf8WNPKvW3lv8tamu24OSPiVdfQu0o1GhUlINlwsYs02Cq/PucVVTcoqAT7hcONp1SnQCFmhfKEoA9F4k8Tmz7+mYnHXXdgWcqiKNhofWtnfpfI1iTMXmc+ibGU5Bt0SBaZHJ0sEJow6MgwCeyA5H3PAXR10kLlUhl6wtpWj0Npa88TuwGHuemgf6nL0bxR9lIQj6mBrEHO4R3+GkkALGquyTjnyOvb1og/4kjcSkNYpevmj3EmbOe8sQLSFzmMwzlQzefYjZJZl0UffMP58IsCgLtphd8UFO387rZEBQaei0xiCKiWvIGm6R1d+x4QHRqHpMpyGCmFDA4g0yvuMfbuaNwvlSHIDk/mFv8QI11hY0dksEhsAxo53jjrj7WdaKKG1RtNOSKLbeo8gC9TLCTpHzp1cwpWSpPpszwWyOu0e2d8PTCdr3gYb8reNKzOdpUfb8W/ky/hb+paOCHyLhp3xxeFoExC2JCPjGoS3yz8/ZR2m3O4iSrvjGLrczi+87sah0sVMj4gsuS3jIxhIbr8SAmBBjqJx2r8OeoMPm8jJMHXCjhIUyqqh+XLb+7QA6prWAhQ68u2w/dnngQVZrK4FbZTYqvfyXOFWTruSV8pturrCWFWzmqFgPlVOuSzbUReHNc+m/KI=
